# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amuro/CS485/Project1Bug/BugCPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amuro/CS485/Project1Bug/BugCPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amuro/CS485/Project1Bug/BugCPP/CMakeFiles /home/amuro/CS485/Project1Bug/BugCPP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amuro/CS485/Project1Bug/BugCPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RunBug

# Build rule for target.
RunBug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RunBug
.PHONY : RunBug

# fast build rule for target.
RunBug/fast:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/build
.PHONY : RunBug/fast

# target to build an object file
src/BugAlgorithms.o:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/BugAlgorithms.o
.PHONY : src/BugAlgorithms.o

# target to preprocess a source file
src/BugAlgorithms.i:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/BugAlgorithms.i
.PHONY : src/BugAlgorithms.i

# target to generate assembly for a file
src/BugAlgorithms.s:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/BugAlgorithms.s
.PHONY : src/BugAlgorithms.s

# target to build an object file
src/Graphics.o:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/Graphics.o
.PHONY : src/Graphics.o

# target to preprocess a source file
src/Graphics.i:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/Graphics.i
.PHONY : src/Graphics.i

# target to generate assembly for a file
src/Graphics.s:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/Graphics.s
.PHONY : src/Graphics.s

# target to build an object file
src/Simulator.o:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/Simulator.o
.PHONY : src/Simulator.o

# target to preprocess a source file
src/Simulator.i:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/Simulator.i
.PHONY : src/Simulator.i

# target to generate assembly for a file
src/Simulator.s:
	$(MAKE) -f CMakeFiles/RunBug.dir/build.make CMakeFiles/RunBug.dir/src/Simulator.s
.PHONY : src/Simulator.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RunBug"
	@echo "... src/BugAlgorithms.o"
	@echo "... src/BugAlgorithms.i"
	@echo "... src/BugAlgorithms.s"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/Simulator.o"
	@echo "... src/Simulator.i"
	@echo "... src/Simulator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

